name: mingw32-make

on:
  push:
    branches: [ "indev", "sf_ai" ]
jobs:
  build:
    permissions: write-all
    runs-on: windows-2019
    steps:
    - name: checkout code
      uses: actions/checkout@v4
      
    - name: Set up MinGW
      uses: egor-tensin/setup-mingw@v2
      with:
        platform: x86
        version: 12.2.0 

    - name: "Setup"
      run: |
        gcc --version

    - name: Compile Project
      run: |
        mingw32-make --version
        mingw32-make clean
        mingw32-make --debug

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: sfsf-artifact
        path: bin/sfsf.asi
